# Generated by Django 4.2.1 on 2023-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='profile',
            field=models.FileField(null=True, upload_to='subscriber_profile_photo/'),
        ),
    ]
