# Generated by Django 4.1.7 on 2023-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriber_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, null=True),
        ),
    ]
