# Generated by Django 4.1.7 on 2023-05-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_is_active_userrole_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
    ]
